version: '3.8'

services:
  gateway-api:
    build:
      context: ./src/Services/Gateway.API
      dockerfile: Dockerfile
    container_name: gateway-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__NotificationAPI=http://notification-api
      - Services__SubscriptionAPI=http://subscription-api
    networks:
      - notification-network
    depends_on:
      - notification-api
      - subscription-api

  notification-api:
    build:
      context: ./src/Services/Notification.API
      dockerfile: Dockerfile
    container_name: notification-api
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CosmosDB=AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - ConnectionStrings__ServiceBus=Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=fake
    networks:
      - notification-network

  subscription-api:
    build:
      context: ./src/Services/Subscription.API
      dockerfile: Dockerfile
    container_name: subscription-api
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CosmosDB=AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge 