version: '3.8'

services:
  gateway-api:
    build:
      context: ./src/Services/Gateway.API
      dockerfile: Dockerfile
    container_name: gateway-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__NotificationAPI=http://notification-api
      - Services__SubscriptionAPI=http://subscription-api
    networks:
      - notification-network
    depends_on:
      - notification-api
      - subscription-api

  notification-api:
    # A ser implementado
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: notification-api
    networks:
      - notification-network

  subscription-api:
    # A ser implementado
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: subscription-api
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge 